### ISSUE TITLE
Support Tags (multiple) in all relevant Invoke cmdlets

### ISSUE THREAD

**Issue by rasmusjelsgaard** [3shapeAS/docker-ci#22]
- Make Invoke-DockerBuild, Invoke-DockerTag and Invoke-DockerPush support supplying multiple tags as input.
- Add tests for these cases.
- They should support the input as parameters from pipeline object properties.

**Comment by casz** [comment]
Could you be more specific, like adding an description? not sure what you mean `support multiple tags` where and what are you trying to solve?

**Comment by rasmusjelsgaard** [comment]
Docker doesn't support multiple tags in one go currently, so closing this.

**Comment by casz** [comment]
I also think this problem is partly solved by docker manifest 👍 closing
